version: '3.8'

volumes:
  database:
  static_value:
  media_value:
  certbot-etc:
  web-root:

services:

  frontend:
    container_name: foodgram_frontend
    image: vorvorsky/foodgram_frontend:v1.02
    volumes:
      - ../frontend/:/app/result_build/

  db:
    container_name: foodgram_db
    image: postgres:15.1-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram_backend
    image: vorvorsky/foodgram_backend:v1.08
    restart: always
    command: >
      bash -c "gunicorn foodgram.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: foodgram_nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx_server.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static/
      - media_value:/app/media/
      - web-root:/var/html/www/
      - certbot-etc:/etc/letsencrypt/
    depends_on:
      - backend
